export interface Ischools{
    SchoolSessionId : number,
    SchoolCode : string,
    SchoolYear : string,
    SchoolName: string,
    SchoolAddress: string,
    City: string,
    StateName: string,
    StateCode: number,
    Latitude: number,
    Longitude: number,
    AllowEmailInvoicing: boolean,
    AllowCCs: boolean,
    IsCharterSchool: boolean,
    DepositRequired: boolean,
    PolicyAgreementType: string,
    PolicyAgreementText: string,
    HasCustomPolicyAgreement: boolean,
    CustomPolicyAgreementObjectKey :string,
    HasSchoolLogo: boolean,
    SchoolLogoUrl: string,
    Distance : string,
    AdditionalAgreementText: string,
    AdditionalConfirmationMessage: string,
    ElectronicFailFee: string,
    CheckFailFee: string,
    DioceseId: number,
    SchoolType: string,
    DisableNewFamilyEnrollment: boolean,
    SmartShieldUrl: string,
    IsSmartShieldActive: boolean,
    IsStateEligibleForSmart: boolean

}